/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserProfile = IDL.Record({
  'nip' : IDL.Text,
  'latitude' : IDL.Float64,
  'desa' : IDL.Text,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'kecamatan' : IDL.Text,
  'address' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const EmployeeProfile = IDL.Record({
  'id' : IDL.Principal,
  'nip' : IDL.Text,
  'latitude' : IDL.Float64,
  'desa' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'longitude' : IDL.Float64,
  'kecamatan' : IDL.Text,
  'address' : IDL.Text,
});
export const PerformanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'adminRating' : IDL.Opt(IDL.Text),
  'employeeName' : IDL.Text,
  'realisasi' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Time,
  'task' : IDL.Text,
  'score' : IDL.Text,
  'target' : IDL.Nat,
  'employeeId' : IDL.Principal,
  'adminFeedback' : IDL.Opt(IDL.Text),
  'percentage' : IDL.Float64,
  'fileBuktiUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminUpdateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateEmployeeProfile' : IDL.Func([EmployeeProfile], [], []),
  'createPerformanceRecord' : IDL.Func(
      [
        IDL.Record({
          'employeeName' : IDL.Text,
          'realisasi' : IDL.Nat,
          'date' : IDL.Text,
          'task' : IDL.Text,
          'score' : IDL.Text,
          'target' : IDL.Nat,
          'employeeId' : IDL.Principal,
          'fileBuktiUrl' : IDL.Opt(IDL.Text),
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEmployeeProfile' : IDL.Func([IDL.Principal], [], []),
  'deletePerformanceRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
  'getAllEmployeeProfiles' : IDL.Func(
      [],
      [IDL.Vec(EmployeeProfile)],
      ['query'],
    ),
  'getAllPerformanceRecords' : IDL.Func(
      [],
      [IDL.Vec(PerformanceRecord)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployeeProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployeeProfile)],
      ['query'],
    ),
  'getPerformanceRecordsByEmployee' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PerformanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRecordFeedback' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserProfile = IDL.Record({
    'nip' : IDL.Text,
    'latitude' : IDL.Float64,
    'desa' : IDL.Text,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'kecamatan' : IDL.Text,
    'address' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const EmployeeProfile = IDL.Record({
    'id' : IDL.Principal,
    'nip' : IDL.Text,
    'latitude' : IDL.Float64,
    'desa' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'longitude' : IDL.Float64,
    'kecamatan' : IDL.Text,
    'address' : IDL.Text,
  });
  const PerformanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'adminRating' : IDL.Opt(IDL.Text),
    'employeeName' : IDL.Text,
    'realisasi' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Time,
    'task' : IDL.Text,
    'score' : IDL.Text,
    'target' : IDL.Nat,
    'employeeId' : IDL.Principal,
    'adminFeedback' : IDL.Opt(IDL.Text),
    'percentage' : IDL.Float64,
    'fileBuktiUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminUpdateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateEmployeeProfile' : IDL.Func([EmployeeProfile], [], []),
    'createPerformanceRecord' : IDL.Func(
        [
          IDL.Record({
            'employeeName' : IDL.Text,
            'realisasi' : IDL.Nat,
            'date' : IDL.Text,
            'task' : IDL.Text,
            'score' : IDL.Text,
            'target' : IDL.Nat,
            'employeeId' : IDL.Principal,
            'fileBuktiUrl' : IDL.Opt(IDL.Text),
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEmployeeProfile' : IDL.Func([IDL.Principal], [], []),
    'deletePerformanceRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
    'getAllEmployeeProfiles' : IDL.Func(
        [],
        [IDL.Vec(EmployeeProfile)],
        ['query'],
      ),
    'getAllPerformanceRecords' : IDL.Func(
        [],
        [IDL.Vec(PerformanceRecord)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployeeProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployeeProfile)],
        ['query'],
      ),
    'getPerformanceRecordsByEmployee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PerformanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRecordFeedback' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };